version: '3.1'

services:
  webserver:
    image: "nginx:latest"
    ports:
      - "8080:80"
    volumes:
      - ./config/webserver/nginx.conf:/etc/nginx/nginx.conf
      - ./config/webserver/default.conf:/etc/nginx/conf.d/default.conf
      - ./html:/usr/share/nginx/html
    networks:
      - no-internet
      - teknixcovpc

  fileserver:
    image: "nginx:latest"
    volumes:
      - ./config/fileserver/nginx.conf:/etc/nginx/nginx.conf
      - ./config/fileserver/default.conf:/etc/nginx/conf.d/default.conf
      - ./files:/usr/share/nginx/html
    networks:
      - no-internet
    depends_on: 
      - reverseproxy

  reverseproxy:
    image: "nginx:latest"
    ports:
      - "8082:80"
    volumes:
      - ./config/reverseproxy/nginx.conf:/etc/nginx/nginx.conf
      - ./config/reverseproxy/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - teknixcovpc
      - no-internet
  
  express-server:
    image: "node:latest"
    volumes:
      - ./express/app:/usr/src/app
    working_dir: "/usr/src/app"
    command: "sh -c 'npm i && npm run start'"
    networks:
      - no-internet

networks:
  teknixcovpc:
    driver: bridge
  no-internet:
    internal: true
