version: '3.1'

services:
  reverseproxy:
    image: "nginx:latest"
    ports:
      - "8080:80"
      - "8443:443"
    networks:
      - teknixcovpc
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./default.conf:/etc/nginx/conf.d/default.conf

networks:
  teknixcovpc:
    driver: bridge
