version: '3.1'

services:
  webserver:
    image: "nginx:latest"
    ports:
      - "8080:80"
    volumes:
      - ./config/webserver/nginx.conf:/etc/nginx/nginx.conf
      - ./config/webserver/default.conf:/etc/nginx/conf.d/default.conf
      - ./html:/usr/share/nginx/html
    networks:
      - no-internet
      - teknixcovpc

  fileserver:
    image: "nginx:latest"
    volumes:
      - ./config/fileserver/nginx.conf:/etc/nginx/nginx.conf
      - ./config/fileserver/default.conf:/etc/nginx/conf.d/default.conf
      - ./files:/usr/share/nginx/html
    networks:
      - teknixcovpc
      - no-internet
    depends_on: 
      - reverseproxy

  reverseproxy:
    image: "nginx:latest"
    ports:
      - "8082:80"
    volumes:
      - ./config/reverseproxy/nginx.conf:/etc/nginx/nginx.conf
      - ./config/reverseproxy/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - teknixcovpc
      - no-internet

networks:
  teknixcovpc:
    driver: bridge
  no-internet:
    internal: true
